/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';
import {GLTF} from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Body: THREE.Mesh;
    Transparent: THREE.Mesh;
    Transparent001: THREE.Mesh;
    Fog: THREE.Mesh;
    Signal002: THREE.Mesh;
    Lights001: THREE.Mesh;
    Lights002: THREE.Mesh;
    Lights: THREE.Mesh;
    SideSkirt: THREE.Mesh;
    Trim: THREE.Mesh;
    Trim001: THREE.Mesh;
    Trim002: THREE.Mesh;
    Mirror: THREE.Mesh;
    Taillight: THREE.Mesh;
    Taillight001: THREE.Mesh;
    Taillight002: THREE.Mesh;
    Taillight003: THREE.Mesh;
    Sphere: THREE.Mesh;
    Windows: THREE.Mesh;
    Underbody: THREE.Mesh;
    Amblem: THREE.Mesh;
    Text: THREE.Mesh;
    Wheel: THREE.Mesh;
    Wheel001: THREE.Mesh;
    Wheel002: THREE.Mesh;
    Wheel003: THREE.Mesh;
    Signal: THREE.Mesh;
    Signal001: THREE.Mesh;
    Taillight004: THREE.Mesh;
    Taillight005: THREE.Mesh;
    Taillight006: THREE.Mesh;
    Sphere001: THREE.Mesh;
    Sphere002: THREE.Mesh;
    Wheel004: THREE.Mesh;
    Wheel005: THREE.Mesh;
    Wheel006: THREE.Mesh;
    Wheel007: THREE.Mesh;
    Circle: THREE.Mesh;
    Plane033: THREE.Mesh;
    Plane034: THREE.Mesh;
    Circle010: THREE.Mesh;
    Circle010_1: THREE.Mesh;
    Circle011: THREE.Mesh;
    Circle011_1: THREE.Mesh;
    Circle012: THREE.Mesh;
    Circle012_1: THREE.Mesh;
    Circle013: THREE.Mesh;
    Circle013_1: THREE.Mesh;
  };
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial;
    ['Material.024']: THREE.MeshStandardMaterial;
    ['Material.010']: THREE.MeshStandardMaterial;
    ['Material.013']: THREE.MeshStandardMaterial;
    ['Material.012']: THREE.MeshStandardMaterial;
    ['Material.006']: THREE.MeshStandardMaterial;
    ['Material.026']: THREE.MeshStandardMaterial;
    ['Material.029']: THREE.MeshStandardMaterial;
    ['Material.014']: THREE.MeshStandardMaterial;
    ['Material.034']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.007']: THREE.MeshStandardMaterial;
    ['Material.005']: THREE.MeshStandardMaterial;
    ['Material.018']: THREE.MeshStandardMaterial;
    ['Material.025']: THREE.MeshStandardMaterial;
    ['Material.027']: THREE.MeshStandardMaterial;
    ['Material.028']: THREE.MeshStandardMaterial;
    ['Material.031']: THREE.MeshStandardMaterial;
    ['Material.033']: THREE.MeshStandardMaterial;
    ['Material.020']: THREE.MeshStandardMaterial;
    ['Material.022']: THREE.MeshStandardMaterial;
    ['Material.023']: THREE.MeshStandardMaterial;
    ['Material.016']: THREE.MeshStandardMaterial;
    ['Material.032']: THREE.MeshStandardMaterial;
    ['Material.003']: THREE.MeshStandardMaterial;
    ['Material.004']: THREE.MeshStandardMaterial;
    ['Material.063']: THREE.MeshStandardMaterial;
    ['Material.008']: THREE.MeshStandardMaterial;
    ['Material.009']: THREE.MeshStandardMaterial;
  };
};

export function Porsche(props: JSX.IntrinsicElements['group']) {
  const {nodes, materials} = useGLTF(
    require('../../assets/3DModels/porsche_glb.glb'),
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={1} position={[0, -1.4, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body.geometry}
        material={materials['Material.001']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Transparent.geometry}
        material={materials['Material.024']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Transparent001.geometry}
        material={materials['Material.010']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fog.geometry}
        material={materials['Material.013']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Signal002.geometry}
        material={materials['Material.012']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lights001.geometry}
        material={materials['Material.006']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lights002.geometry}
        material={materials['Material.026']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lights.geometry}
        material={materials['Material.029']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SideSkirt.geometry}
        material={materials['Material.026']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trim.geometry}
        material={materials['Material.026']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trim001.geometry}
        material={materials['Material.026']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trim002.geometry}
        material={materials['Material.014']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mirror.geometry}
        material={materials['Material.034']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Taillight.geometry}
        material={materials['Material.002']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Taillight001.geometry}
        material={materials['Material.012']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Taillight002.geometry}
        material={materials['Material.007']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Taillight003.geometry}
        material={materials['Material.005']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials['Material.018']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Windows.geometry}
        material={materials['Material.025']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Underbody.geometry}
        material={materials['Material.027']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Amblem.geometry}
        material={materials['Material.028']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials['Material.031']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel.geometry}
        material={materials['Material.033']}
        position={[0.863, 0.318, 1.211]}
        rotation={[-Math.PI / 2, 1.571, 0]}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel001.geometry}
        material={materials['Material.033']}
        position={[0.863, 0.318, -1.057]}
        rotation={[-Math.PI / 2, 1.571, 0]}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel002.geometry}
        material={materials['Material.033']}
        position={[-0.863, 0.318, 1.211]}
        rotation={[-Math.PI / 2, 1.571, 0]}
        scale={[1.487, 1.487, -1.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel003.geometry}
        material={materials['Material.033']}
        position={[-0.863, 0.318, -1.057]}
        rotation={[-Math.PI / 2, 1.571, 0]}
        scale={[1.487, 1.487, -1.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Signal.geometry}
        material={materials['Material.012']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Signal001.geometry}
        material={materials['Material.024']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Taillight004.geometry}
        material={materials['Material.020']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Taillight005.geometry}
        material={materials['Material.022']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Taillight006.geometry}
        material={materials['Material.023']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={materials['Material.016']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002.geometry}
        material={materials['Material.029']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel004.geometry}
        material={materials['Material.032']}
        position={[0.863, 0.318, 1.211]}
        rotation={[-Math.PI / 2, 1.571, 0]}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel005.geometry}
        material={materials['Material.032']}
        position={[0.863, 0.318, -1.057]}
        rotation={[-Math.PI / 2, 1.571, 0]}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel006.geometry}
        material={materials['Material.032']}
        position={[-0.863, 0.318, 1.211]}
        rotation={[-Math.PI / 2, 1.571, 0]}
        scale={[1.487, 1.487, -1.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel007.geometry}
        material={materials['Material.032']}
        position={[-0.863, 0.318, -1.057]}
        rotation={[-Math.PI / 2, 1.571, 0]}
        scale={[1.487, 1.487, -1.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials['Material.003']}
        scale={1.487}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane033.geometry}
        material={materials['Material.004']}
        position={[0.025, 3.259, -1.404]}
        rotation={[-0.139, -1.571, 0]}
        scale={[1, 1, 0.176]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane034.geometry}
        material={materials['Material.063']}
        position={[0.011, -0.002, 1.293]}
      />
      <group
        position={[0.764, 0.318, 1.211]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.487}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle010.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle010_1.geometry}
          material={materials['Material.009']}
        />
      </group>
      <group
        position={[0.792, 0.318, -1.057]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.487}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle011.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle011_1.geometry}
          material={materials['Material.009']}
        />
      </group>
      <group
        position={[-0.764, 0.318, 1.211]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.487, -1.487, 1.487]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle012.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle012_1.geometry}
          material={materials['Material.009']}
        />
      </group>
      <group
        position={[-0.792, 0.318, -1.057]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.487, -1.487, 1.487]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle013.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle013_1.geometry}
          material={materials['Material.009']}
        />
      </group>
    </group>
  );
}