export enum ROUTES {
  HOME = 'HOME',
  PROFILE = 'PROFILE',
  ORDERS = 'ORDERS',
  WALLET = 'WALLET',
  NOTIFICATION = 'NOTIFICATION',
  SPECIAL_OFFER = 'SPECIAL_OFFER',
  TOP_DEALS = 'TOP_DEALS',
}
