# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Expo modules autolinking
require File.join(File.dirname(`node --print "require.resolve('expo/package.json', { paths: ['#{__dir__}'] })"`), "scripts/autolinking")

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'carea' do
  config = use_native_modules!

  use_expo_modules!(exclude: ['expo-gl'])

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'careaTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'hermes-engine'
        target.build_phases.each do |build_phase|
          if build_phase.respond_to?(:name) && build_phase.name.include?('[CP-User] [Hermes]')
            build_phase.output_paths = ['${PODS_ROOT}/hermes-engine/destroot/Library/Frameworks/hermes.framework']
          end
        end
      end
    end
    # Patch React imports for pods with modular headers enabled by use_expo_modules!
    expo_patch_react_imports!(installer)

    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Add the following block to update deployment target for all pods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version_supported
        # ExpoGL C++ files are not compatible with c++20; use c++17 for that target
        if target.name == 'ExpoGL'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end
  end
end